# Generated by Django 5.0.4 on 2024-05-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240524_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
